//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDemo8
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReviews
    {
        public int ReviewId { get; set; }
        public string UserId { get; set; }
        public string BookTitle { get; set; }
        public string ReviewContent { get; set; }
        public int Rating { get; set; }
        public string Category { get; set; }
        public string ImageUrl { get; set; }
        public string PurchaseLink { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
