//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDemo8
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorePosts
    {
        public int PostId { get; set; }
        public int StoreId { get; set; }
        public string BookTitle { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Stores Stores { get; set; }
    }
}
